filter:
  paths:
    - 'src/*'
  dependency_paths:
    - 'vendor/*'

build:
  environment:
    php:
      version: '7.2'
      ini:
        'always_populate_raw_post_data': '-1'

  dependencies:
    before:
      - sed -i 's/zend_extension_ts=xdebug.so/;zend_extension_ts=xdebug.so/' ~/.phpenv/versions/$(phpenv global)/etc/php.ini
      - composer global require "hirak/prestissimo:^0.3"

    override:
      - { command: 'composer install --no-interaction --no-suggest -vv', idle_timeout: 600 }
      - { command: 'cd magento2-test-env && composer install --no-interaction --no-suggest -vv && cd -', idle_timeout: 600 }

  cache:
    directories: [ ~/.composer/cache ]

  nodes:
    analysis:
      project_setup:
        override:
          - cd magento2-test-env
          - sudo apt-get update && sudo apt-get purge -y mysql-server*
          - echo mysql-server mysql-server/root_password password root | sudo debconf-set-selections
          - echo mysql-server mysql-server/root_password_again password root | sudo debconf-set-selections
          - sudo apt-get install -y mysql-server-core-5.6 mysql-server-5.6
          - ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock
          - mysql -uroot -proot -e "create database magento"
          - bin/magento setup:install --admin-email "kotosy@gmail.com" --admin-firstname "admin" --admin-lastname "admin" --admin-password "admin123" --admin-user "admin" --backend-frontname admin --base-url "http://magento.test" --db-host 127.0.0.1 --db-name magento --db-user root --db-password root --session-save files --use-rewrites 1 --use-secure 0 -vvv
          - bin/magento setup:upgrade
          - cd ..
      tests:
        override:
          - find src/ -type f \( -name '*.phtml' -o -name '*.php' \) | xargs -n 1 -P 8 -i php -l {} | grep -v 'No syntax errors detected' || echo 'OK'
          - php-scrutinizer-run
          - bin/behat -swithout_compiled_di --no-interaction --no-snippets --stop-on-failure --format=pretty
          - bin/behat -swith_compiled_di --no-interaction --no-snippets --stop-on-failure --format=pretty

build_failure_conditions:
  - 'elements.rating(< A).new.exists'
  - 'issues.label("coding-style").new.exists'
  - 'issues.new.exists'
  - 'project.metric("scrutinizer.quality", < 9.00)'
